
data_dir: "./data/dev"
models_dir: "./models/dev"
cache_dir: "./cache/dev"

logging:
  level: "DEBUG"
  console: true
  file: "./logs/ragnificent-dev.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

scraper:
  rate_limit: 1.0  # Higher rate limit for development
  cache_enabled: true
  cache_max_age: 86400  # 24 hours
  timeout: 30
  max_workers: 4  # Fewer workers for development
  domain_rate_limits:
    "example.com": 2.0
    "*.python.org": 5.0
  adaptive_throttling: true
  use_rust_implementation: true

chunking:
  strategy: "semantic"
  chunk_size: 1000
  chunk_overlap: 200
  separator: "\n"
  keep_separator: true

embedding:
  model_type: "sentence_transformer"
  model_name: "BAAI/bge-small-en-v1.5"  # Smaller model for development
  batch_size: 16
  device: "cpu"
  use_cache: true
  normalize: true

qdrant:
  host: ":memory:"  # In-memory for development
  port: 6333
  collection: "ragnificent_dev"
  vector_size: 384
  timeout: 10
  prefer_grpc: true

openai:
  embedding_model: "text-embedding-3-small"
  completion_model: "gpt-3.5-turbo"
  max_tokens: 1000
  temperature: 0.7
  request_timeout: 30
  max_retries: 3

search:
  max_results: 5
  score_threshold: 0.6
  use_hybrid_search: false
  rate_limit_per_minute: 60
  enable_caching: true
  cache_ttl: 3600

resources:
  max_memory_percent: 80.0
  max_connections: 50
  max_thread_workers: 10
  cleanup_interval: 60
  enable_monitoring: true

features:
  enable_advanced_chunking: true
  enable_parallel_processing: true
  enable_memory_optimization: true
  enable_caching: true
  enable_benchmarking: true
  enable_security_features: true
