name: RAGnificent CI

permissions:
  contents: read

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Check compilation
        run: cargo check --verbose

      - name: Run tests
        run: cargo test --verbose

  python-tests:
    name: Python ${{ matrix.python-version }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install build dependencies
        run: uv pip install maturin

      - name: Install project and dependencies
        run: |
          uv pip install --upgrade pip
          uv pip install .[dev,test]

      - name: Lint with ruff
        run: |
          uv pip install ruff
          ruff check .

      - name: Type check with mypy
        run: |
          uv pip install mypy
          mypy RAGnificent/

      - name: Run tests
        run: |
          python -m pytest -v --tb=short

      - name: Test package builds correctly
        run: |
          uv pip install build
          python -m build
